derp/core/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from core import views
from core.forms import LoginForm


app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path(
        "login/",
        LoginView.as_view(
            template_name="core/login.html", authentication_form=LoginForm
        ),
        name="login",
    ),
    path("logout/", views.logout_user, name="logout"),
    path("menu/", views.menu, name="menu"),
]

derp/derp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('__reload__/', include('django_browser_reload.urls')),
    path('items/', include('items.urls')),
    path('wearhouse/', include('wearhouse.urls')),
]

derp/wearhouse/urls.py
# pylint: disable=invalid-name, missing-module-docstring
from django.urls import path
from . import views


app_name = 'wearhouse'

urlpatterns = [
    path('master/', views.master_file, name='master'),
    path('delete/<uuid:uuid>', views.delete, name='delete'),
    path('update-inline/<uuid:uuid>', views.update_inline, name='update-inline'),
    path('inline/<uuid:uuid>', views.inline, name='inline'),
    path('new/', views.new, name='new'),
    path('new-inline/', views.new_inline, name='new-inline'),
]

derp/wearhouse/models.py
# pylint: disable=missing-module-docstring,invalid-str-returned, invalid-repr-returned
from django.db import models
from django.utils.translation import gettext_lazy as _
from django_extensions.db.models import TimeStampedModel
from utils import abstract_models
from items.models import Item


class Wearhouse(
    TimeStampedModel,
    abstract_models.Model,
    abstract_models.UserOperations):
    """Basic information about a wearhouse
    AM.Model: uuid instead of simple id
    AM.UserOperation: created by and last modified by
    """
    name = models.CharField(max_length=25, null=False, blank=False, unique=True)
    description = models.TextField(null=True)
    address = models.CharField(max_length=50, null=False, blank=False)
    stockunits = models.ForeignKey(
        'wearhouse.StockUnit',
        verbose_name=_('Stock units'),
        on_delete=models.CASCADE,
        null=True  # TODO da togliere poi
    )

    class Meta:
        """Meta information about the table
        """
        verbose_name_plural = 'Wearhouses'
        db_table = 'wearhouses'
        db_table_comment = 'Wearhouse basic information'
        get_latest_by = '-modified'
        ordering = ['name']

    def __str__(self) -> str:
        return self.name 


class StockUnit(
    TimeStampedModel,
    abstract_models.Model,
    abstract_models.UserOperations):
    """Basic unit of a wearhouse
    Each stockunit is capable of containing a certain amount of a 
    specific item. It also carries information about the current state.
    """
    name = models.CharField(_("Stock unit name"), max_length=51, unique=True)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    stored_quantity = models.FloatField(_('Stored quantity'), null=False)
    max_quantity = models.FloatField(_('Maximum quantity'), null=False, blank=False)

    class Meta:
        """Meta information about the table
        """
        verbose_name_plural = 'Stock units'
        db_table = 'stockunits'
        get_latest_by = '-modified'

    def __str__(self) -> str:
        return f'{self.name}: {self.stored_quantity}/{self.max_quantity}'

    def __repr__(self) -> str:
        return self.name

derp/wearhouse/forms.py
# pylint: disable=missing-class-docstring,missing-module-docstring
from django import forms

from .models import Wearhouse


BASIC_STYLE = 'rounded-lg w-full'


class WearhouseForm(forms.ModelForm):
    class Meta:
        model = Wearhouse
        fields = ['name', 'description', 'address']
        widgets = {
            'name': forms.TextInput(attrs={
                'class': BASIC_STYLE,
                'placeholder': 'Some name'
            }),
            'description': forms.Textarea(attrs={
                'class': BASIC_STYLE,
                'placeholder': 'Some brief description'
            }),
            'address': forms.TextInput(attrs={
                'class': BASIC_STYLE,
                'placeholder': 'Wearhouse address'
            })
        }

derp/wearhouse/views.py
# pylint: disable=no-member, missing-module-docstring
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse

from .forms import WearhouseForm
from .models import Wearhouse


EMPTY_TEMPLATE = 'core/empty.html'
WEARHOUSE_MASTER_FILE = 'wearhouse/master_file.html'
WEARHOUSE_INLINE_RECORD = 'wearhouse/inline_record.html'
WEARHOUSE_CONFIRM_DELETE = 'wearhouse/confirm_delete.html'
WEARHOUSE_UPDATE_INLINE = 'wearhouse/update_inline.html'
WEARHOUSE_ADD_WEARHOUSE = 'wearhouse/add_wearhouse.html'
WEARHOUSE_ADD_INLINE = 'wearhouse/add_wearhouse_inline.html'


@login_required
def master_file(request: HttpRequest) -> HttpResponse:
    """Get all records from the db table
    """
    wearhouses = Wearhouse.objects.all()
    return render(request, WEARHOUSE_MASTER_FILE, {'wearhouses': wearhouses})


@login_required
def inline(request: HttpRequest, uuid: str) -> HttpResponse:
    """Get a single record inline for table view
    Raise 404 if no wearhouse is found
    """
    wearhouse = get_object_or_404(Wearhouse, pk=uuid)
    return render(request, WEARHOUSE_INLINE_RECORD, {'wearhouse': wearhouse})


@login_required
def delete(request: HttpRequest, uuid: str) -> HttpResponse:
    """View to delete a specific wearhouse
    GET: return the dialog to ask for deletion confirmation
    DELETE: perform the deletion and return empty html to 'remove from screen'
    Raise 404 if no wearhouse is found
    """
    wearhouse = get_object_or_404(Wearhouse, pk=uuid)
    if request.method == 'DELETE':
        wearhouse.delete()
        return render(request, EMPTY_TEMPLATE)
    return render(request, WEARHOUSE_CONFIRM_DELETE, {'wearhouse': wearhouse})


@login_required
def update_inline(request: HttpRequest, uuid: str) -> HttpResponse:
    """View to update a wearhouse from the table
    GET: return the inline update 'form' with current fiel values
    POST: update the record and return the inline record
    Raise 404 if no wearhouse is found
    """
    wearhouse = get_object_or_404(Wearhouse, pk=uuid)
    if request.method == 'POST':
        wearhouse.name = request.POST['name']
        wearhouse.description = request.POST['description']
        wearhouse.address = request.POST['address']
        wearhouse.last_modified_by = request.user # type: ignore
        wearhouse.save()
        return render(request, WEARHOUSE_INLINE_RECORD, {'wearhouse': wearhouse})
    return render(request, WEARHOUSE_UPDATE_INLINE, {'wearhouse': wearhouse})


@login_required
def new(request: HttpRequest) -> HttpResponse:
    """View to add a new Wearhouse with a dialog form
    GET: return the empty form
    POST: save the new record and redirect to master TODO: this has to change
    TODO good place to introduce the role of user_groups
    """
    if request.method == 'POST':
        form = WearhouseForm(request.POST)
        if form.is_valid():
            wearhouse: Wearhouse = form.save()
            wearhouse.created_by = request.user # type: ignore
            wearhouse.save()
            return redirect('/wearhouse/master')
    form = WearhouseForm()
    return render(request, WEARHOUSE_ADD_WEARHOUSE, {'form': form})


@login_required
def new_inline(request: HttpRequest) -> HttpResponse:
    """View to add a new Wearhouse with the inline "form"
    GET: return the inline empty inputs
    POST: save the new record and return the inline record template
    """
    if request.method == 'POST':
        wearhouse = Wearhouse()
        wearhouse.name = request.POST['name']
        wearhouse.description = request.POST['description']
        wearhouse.address = request.POST['address']
        wearhouse.created_by = request.user # type: ignore
        wearhouse.save()
        return render(request, WEARHOUSE_INLINE_RECORD, {'wearhouse': wearhouse})
    return render(request, WEARHOUSE_ADD_INLINE)


@login_required
def assigne_stock_units(request: HttpRequest) -> HttpResponse:
    # TODO this method should check for wearhouse existence and add stockunits to it
    pass

derp/wearhouse/templates/wearhouse/add_wearhouse.html
{% extends "core/modal_dialog.html" %}

{% block content %}
<div class="p-6 shadow-lg rounded-lg overflow-hidden w-1/2 bg-slate-100">
    <h2 class="text-teal-700 font-bold capitalize text-lg align-middle text-center">New Wearhouse</h2>
    <form method="POST" action={% url "wearhouse:new" %} enctype="multipart/from-data">
        {% csrf_token %}
        <div class="space-y-4">
            {{ form.as_p }}
        </div>
        {% if form.errors or form.non_field_errors %}
        <div>
            {% for field in form  %}
                {{ field.errors }}
            {% endfor %}
            {{ form.non_field_errors }}
        </div>
        {% endif %} 
        {% include "core/submit_cancel.html" %}
    </form>
</div>
{% endblock content %}

derp/wearhouse/templates/wearhouse/add_wearhouse_inline.html
<tr id="new-wearhouse" class="odd:bg-slate-50 even:bg-slate-200">
    <td scope="row" class="px-4 font-semibold">
        <input type="text" name="name" value="{{ wearhouse.name }}" class="rounded-lg w-full">
    </td>
    <td scope="row" class="py-2 px-4">
        <input name="description" value="{{ wearhouse.description }}" class="rounded-lg w-full">
    </td>
    <td scope="row", class="py-2 px-4">
        <input name="address" value="{{ wearhouse.address}}" class="rounded-lg w-full">
    </td>
    <td scope="row">
        {% csrf_token %}
        <button 
            type="button"
            _="on click remove #new-wearhouse">
            <span class="material-symbols-rounded text-slate-700" style="font-size: 1.75rem" title="Undo changes">undo</span>
        </button>
        <button 
            type="button"
            hx-post={% url "wearhouse:new-inline" %}
            hx-target="#new-wearhouse"
            hx-swap="outerHTML"
            hx-include="[name='name'], [name='description'], [name='address']">
            <span class="material-symbols-rounded text-slate-700" style="font-size: 1.75rem" title="Save">save</span>
        </button>
    </td>
  </tr>

derp/wearhouse/templates/wearhouse/assign_stock_units.html
<div>
    
</div>

derp/wearhouse/templates/wearhouse/confirm_delete.html
{% extends "core/modal_dialog.html" %}
{% block content %}
<div class="p-6 shadow-lg rounded-lg overflow-hidden w-1/3 bg-slate-100">
    <h2 class="text-red-700 font-bold capitalize text-lg align-middle text-center my-2">Delete {{ wearhouse.name }}</h2>
    <p class="space-y-4 text-slate-700 text-lg mt-4 mb-8">Are you sure you want to delete the selected wearhouse?</p>
    <div class="flex items-baseline">
    <button 
        type="button"
        class="p-2 m-2 bg-teal-700 text-slate-50 font-semibold rounded-lg w-full hover:bg-yellow-600 hover:text-slate-50"
        hx-delete={% url "wearhouse:delete" wearhouse.id %}
        hx-target="#id-{{wearhouse.id}}" 
        hx-swap="outerHTML swap:1s" 
        _="on click trigger closeModal">
        Delete
    </button>
    <button
        class="p-2 m-2 bg-slate-200 text-teal-700 font-semibold rounded-lg w-full hover:bg-slate-200 hover:text-yellow-600"
        type="button"
        _="on click trigger closeModal">Cancel
    </button>
    </div>
</div>
{% endblock content %}

derp/wearhouse/templates/wearhouse/inline_record.html
<tr id="id-{{wearhouse.id}}" class="odd:bg-slate-50 even:bg-slate-200 fade-me-out">
    <td class="py-2 px-4 font-semibold">{{ wearhouse.name }}</td>
    <td class="py-2 px-4">{{ wearhouse.description }}</td>
    <td class="py-2 px-4">{{ wearhouse.address }} </td>
    <td>
        {% csrf_token %}
        <button 
            type="button"
            hx-get={% url "wearhouse:delete" wearhouse.id %} 
            hx-target="body" 
            hx-swap="beforeend" 
            hx-trigger="click">
            <span class="material-symbols-rounded text-slate-700" style="font-size: 1.75rem" title="Delete this item">delete</span>
        </button>
        <button 
            type="button"
            hx-get={% url "wearhouse:update-inline" wearhouse.id %}
            hx-target="#id-{{wearhouse.id}}"
            hx-swap="outerHTML">
            <span class="material-symbols-rounded text-slate-700" style="font-size: 1.75rem" title="Edit this item">edit</span>
        </button>
    </td>
</tr>

derp/wearhouse/templates/wearhouse/master_file.html
{% extends "core/base.html" %}

{% block title %}Wearhouses{% endblock title %}

{% block content %}
<!--BUTTONS-->
<div>
    <button 
        class="mt-4 m-2 p-2 rounded-lg bg-teal-700 text-slate-50 font-semibold 
        hover:bg-slate-100 hover:text-yellow-500" 
        hx-get={% url "wearhouse:new" %} 
        hx-target="body" 
        hx-swap="beforeend" 
        hx-trigger="click">Add new wearhouse
    </button>
</div>

<!--GRID-->
<div id="grid" class="mx-2 mt-6 relative overflow-x-auto shadow-md rounded-lg">
    <table class="w-full text-m text-left table-auto border-collapse">
        <thead class="bg-teal-700 text-slate-50">
        <tr>
            <th scope="col" class="py-2 px-4">Name</th>
            <th scope="col" class="py-2 px-4">Description</th>
            <th scope="col" class="py-2 px-4">Address</th>
            <th scope="col" class="py-2 px-4">Actions</th>
        </tr>
        </thead> 
        <tbody>
        {% for wearhouse in wearhouses %}
            {% include "wearhouse/inline_record.html" %}
        {% endfor %}
        </tbody>
    </table>
</div>

<!--NEW LINE-->
<div class="mx-2 mt-2 relative overflow-x-auto h-8">
    <a 
        type="button"
        hx-get={% url "wearhouse:new-inline" %}
        hx-target="tbody > tr:last-child"
        hx-swap="afterend"
        class="py-1 px-2 font-semibold cursor-pointer">
        <span class="material-symbols-rounded text-green-600" style="font-size: 1.5rem" title="Create a new row">add</span>
    </a>
</div>
{% endblock content %} 

derp/wearhouse/templates/wearhouse/update_inline.html
<tr id="id-{{wearhouse.id}}" class="odd:bg-slate-50 even:bg-slate-200">
    <td scope="row" class="px-4 font-semibold">
        <input type="text" name="name" value="{{ wearhouse.name }}" class="rounded-lg w-full">
    </td>
    <td scope="row" class="py-2 px-4">
        <input type="text" name="description" value="{{ wearhouse.description }}" class="rounded-lg w-full"></input>
    </td>
    <td scope="row" class="py-2 px-4">
        <input type="text" name="address" value="{{ wearhouse.address }}" class="rounded-lg w-full"> 
    </td>
    <td scope="row">
        {% csrf_token %}
        <button 
            type="button"
            hx-get={% url "wearhouse:inline" wearhouse.id %}
            hx-target="#id-{{wearhouse.id}}"
            hx-swap="outerHTML">
            <span class="material-symbols-rounded text-slate-700" style="font-size: 1.75rem" title="Undo changes">undo</span>
        </button>
        <button 
            type="button"
            hx-post={% url "wearhouse:update-inline" wearhouse.id %}
            hx-target="#id-{{wearhouse.id}}"
            hx-swap="outerHTML"
            hx-include="[name='name'], [name='description'], [name='address']">
            <span class="material-symbols-rounded text-slate-700" style="font-size: 1.75rem" title="Save changes">save</span>
        </button>
    </td>
</tr>