derp/core/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from core import views
from core.forms import LoginForm


app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path(
        "login/",
        LoginView.as_view(
            template_name="core/login.html", authentication_form=LoginForm
        ),
        name="login",
    ),
    path("logout/", views.logout_user, name="logout"),
    path("menu/", views.menu, name="menu"),
]

derp/derp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('__reload__/', include('django_browser_reload.urls')),
    path('items/', include('items.urls')),
    path('wearhouse/', include('wearhouse.urls')),
]

derp/items/urls.py
# pylint: disable=invalid-name, missing-module-docstring
from django.urls import path
from . import views


app_name = 'items'

urlpatterns = [
    path('master/', views.master_file, name='master'),
    path('delete/<uuid:uuid>', views.delete_item, name='delete'),
    path('update/inline/<uuid:uuid>', views.update_item_inline, name='update-inline'),
    path('new/', views.new_item, name='new'),
    path('new/inline', views.new_item_inline, name='new-inline'),
    path('detail/<uuid:uuid>', views.item_detail, name='detail'),
    path('inline/<uuid:uuid>', views.inline, name='inline'),
]

derp/items/models.py
from django.db import models
from django_extensions.db.models import TimeStampedModel
from utils import abstract_models
from .modules import measure_units


class Item(
    TimeStampedModel,
    abstract_models.UserOperations,
    abstract_models.Model
    ):
    """Item master file
    """
    name = models.CharField(max_length=20, null=False, unique=True)
    description = models.TextField(null=True, blank=True)
    volume = models.FloatField(verbose_name="Volume", null=False, default=0.)
    weigth = models.FloatField(verbose_name="Weigth", null=False, default=0.)
    volume_measure = models.CharField(
        max_length=5,
        verbose_name="Volume measure unit",
        choices=measure_units.VOLUME,
        default='cm3',
        null=False,
        blank=False
    )
    weigth_measure = models.CharField(
        max_length=10,
        verbose_name="Weigth measure unit",
        choices=measure_units.WEIGTH,
        default='g',
        null=False,
        blank=False
    )
    components = models.ForeignKey(
        'self', 
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        default=None
    )

    class Meta:
        """Model meta information for db
        """
        verbose_name_plural = 'Items'
        db_table = 'items'
        db_table_comment = 'Items basic informations'
        get_latest_by = '-modified'
        ordering = ['name']

    def __str__(self) -> str:  # pylint: disable=E0307
        return self.name

derp/items/forms.py
# pylint: disable=missing-class-docstring,missing-module-docstring
from django import forms
from .models import Item

BASIC_STYLE = "rounded-lg w-full"
DIMENSIONS_STYLE = "rounded-lg w-full"


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            "name",
            "description",
            "volume",
            "weigth",
            "volume_measure",
            "weigth_measure",
        ]
        widgets = {
            "name": forms.TextInput(
                attrs={"class": BASIC_STYLE, "placeholder": "Some name"}
            ),
            "description": forms.Textarea(
                attrs={"class": BASIC_STYLE, "placeholder": "Some brief description"}
            ),
            "volume": forms.NumberInput(attrs={"class": DIMENSIONS_STYLE}),
            "weigth": forms.NumberInput(attrs={"class": f"{DIMENSIONS_STYLE}"}),
            "volume_measure": forms.Select(attrs={"class": BASIC_STYLE}),
            "weigth_measure": forms.Select(attrs={"class": f"{BASIC_STYLE}"}),
        }

derp/items/views.py
# pylint: disable=no-member, missing-module-docstring
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest, HttpResponse
from django.contrib.auth.decorators import login_required

from .models import Item
from .forms import ItemForm
from .modules.measure_units import VOLUME, WEIGTH


@login_required
def master_file(request: HttpRequest) -> HttpResponse:
    """Get all items from db
    """
    items = Item.objects.all()
    return render(request, 'master_file.html', {'items': items})


@login_required
def inline(request: HttpRequest, uuid: str) -> HttpResponse:
    """Return single iteme line for table
    Used to undo the update inline
    """
    item = get_object_or_404(Item, pk=uuid)
    return render(request, 'item_inline.html', {'item': item})


@login_required
def item_detail(request: HttpRequest, uuid: str) -> HttpResponse:
    """Return template of single item detail
    """
    item = get_object_or_404(Item, pk=uuid)
    return render(request, 'item_detail.html', {'item': item})


@login_required
def new_item(request: HttpRequest) -> HttpResponse:
    """Add new Item
    GET: returns the template with the form
    POST: validates and saves the form, then renders the master again
    """
    if request.method == 'POST':
        form = ItemForm(request.POST)
        if form.is_valid():
            item: Item = form.save()
            item.created_by = request.user # type: ignore
            item.save()
            return redirect('/items/master')
    else:
        form = ItemForm()
    return render(request, 'add_item.html', {'form': form})


@login_required
def new_item_inline(request: HttpRequest) -> HttpResponse:
    """Add new item with inline input
    Same as update_item_inline accepts both GET and POST
    With GET returns the template and with POST creates the new record
    """
    if request.method == 'POST':
        item = Item()
        item.name = request.POST['name']
        item.description = request.POST['description']
        item.weigth = float(request.POST['weigth'])
        item.weigth_measure = request.POST['weigth_measure']
        item.volume = float(request.POST['volume'])
        item.volume_measure = request.POST['volume_measure']
        item.created_by = request.user # type: ignore
        item.save()
        return render(request, 'item_inline.html', {'item': item})
    return render(request, 'add_item_inline.html', {'w_options': WEIGTH, 'v_options': VOLUME})


@login_required
def delete_item(request: HttpRequest, uuid: str) -> HttpResponse:
    """Delete a record from Item
    If the record is not found a 404 response is risen
    If called from master file (GET) returns a confirmation dialog
    After deletion the user is redirected to item master page 
    """
    item = get_object_or_404(Item, pk=uuid)
    if request.method == 'DELETE':
        item.delete()
        return render(request, 'core/empty.html')
    return render(request, 'confirm_delete.html', {'item': item})


# TODO: here's some code repetition with the new item view, maybe abstract this?
@login_required
def update_item(request: HttpRequest, uuid: str) -> HttpResponse:
    """Update item from detail dialog
    GET: return the form with the initial of the fields
    POST: updates the record in the database and returns (dialog closing on its own)
    """
    item = get_object_or_404(Item, pk=uuid)
    if request.method == 'POST':
        form = ItemForm(request.POST)
        if form.is_valid():
            item: Item = form.save()
            item.last_modified_by = request.user # type: ignore
            item.save()
            return HttpResponse(status=202)
    else:
        form = ItemForm(initial={
            'name': item.name,
            'descritpion': item.description,
            'weigth': item.weigth,
            'weigth_measure': item.weigth_measure,
            'volume': item.volume,
            'volume_measure': item.volume_measure
        },
        auto_id=False)
    return render(request, 'update_item.html', {'form': form})


@login_required
def update_item_inline(request: HttpRequest, uuid: str) -> HttpResponse:
    """Update a record from Item
    If the record is not found a 404 response is rise
    If GET request the editable table row is returned for htmx swap
    If PUT request the actual update is performed
    """
    item = get_object_or_404(Item, pk=uuid)
    if request.method == 'POST':
        item.name = request.POST['name']
        item.description = request.POST['description']
        item.weigth = float(request.POST['weigth'])
        item.volume = float(request.POST['volume'])
        item.last_modified_by = request.user # type: ignore
        item.save()
        return render(request, 'item_inline.html', {'item': item})
    return render(request, 'update_item_inline.html', {'item': item})

derp/items/templates/add_item.html
{% extends "core/modal_dialog.html" %}

{% block content %}
<div class="p-6 shadow-lg rounded-lg overflow-hidden w-1/2 bg-slate-100">
    <h2 class="text-teal-700 font-bold capitalize text-lg align-middle text-center">New Item</h2>
    <form method="POST" action={% url "items:new" %} enctype="multipart/from-data">
        {% csrf_token %}
        <div class="space-y-4">
            <div>
            <label class="font-semibold text-slate-700 text-center" for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
            {{ form.name }}
            </div>
            <div>
                <label class="font-semibold text-slate-700 text-center" for="{{ form.description.id_for_label }}">{{ form.description.label }}</label>
                {{ form.description }}
            </div>
            <table class="w-full">
            <thead>
                <tr>
                    <th class="w-2/3"><label scope="col" class="font-semibold text-slate-700 text-center" for="{{ form.volume.id_for_label }}">{{ form.volume.label }}</label></th>
                    <th class="w-1/3"><label scope="col" class="font-semibold text-slate-700 text-center" for="{{ form.volume_measure.id_for_label }}">{{ form.volume_measure.label }}</label></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ form.volume }}</td>
                    <td>{{ form.volume_measure }}</td>
                </tr>
            </tbody>
            </table>
            <table class="w-full">
            <thead>
                <tr>
                    <th class="w-2/3"><label class="font-semibold text-slate-700 text-center" for="{{ form.weigth.id_for_label }}">{{ form.weigth.label }}</label></th>
                    <th class="w-1/3"><label class="font-semibold text-slate-700 text-center" for="{{ form.weigth_measure.id_for_label }}">{{ form.weigth_measure.label }}</label></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ form.weigth }}</td>
                    <td>{{ form.weigth_measure }}</td>
                </tr>
            </tbody>
            </table>
        </div>
        {% if form.errors or form.non_field_errors %}
        <div>
            {% for field in form %}
            {{ field.errors }}
            {% endfor %}
        </div>
        {% endif %}
        {% include "core/submit_cancel.html" %}
    </form>
</div>
{% endblock content %}

derp/items/templates/add_item_inline.html
<tr id="new-item" class="odd:bg-slate-50 even:bg-slate-200">
    <td scope="row" class="px-4 font-semibold">
        <input type="text" name="name" value="{{ item.name }}" class="rounded-lg w-full">
    </td>
    <td scope="row" class="py-2 px-4">
        <input name="description" value="{{ item.description }}" class="rounded-lg w-full">
    </td>
    <td scope="row" class="py-2 px-4">
        <input type="number" name="volume" value="{{ item.volume }}" class="rounded-lg w-fit">
        <select name="volume_measure" class="rounded-lg">
            {% for option in v_options %}
            <option value="{{ option.0 }}">{{ option.1 }}</option>
            {% endfor %}
        </select>
    </td>
    <td scope="row" class="py-2 px-4">
        <input type="number" name="weigth" value="{{ item.weigth }}" class="rounded-lg w-fit">
        <select name="weigth_measure" class="rounded-lg">
            {% for option in w_options %}
            <option value="{{ option.0 }}">{{ option.1 }}</option>
            {% endfor %}
        </select>
    </td>
    <td scope="row">
        {% csrf_token %}
        <button 
            type="button"
            _="on click remove #new-item">
            <span class="material-symbols-rounded text-slate-700" style="font-size: 1.75rem" title="Undo changes">undo</span>
        </button>
        <button 
            type="button"
            hx-post={% url "items:new-inline" %}
            hx-target="#new-item"
            hx-swap="outerHTML"
            hx-include="[name='name'], [name='description'], [name='volume'], [name='volume_measure'], [name='weigth'], [name='weigth_measure']">
            <span class="material-symbols-rounded text-slate-700" style="font-size: 1.75rem" title="Save">save</span>
        </button>
    </td>
  </tr>

derp/items/templates/confirm_delete.html
{% extends "core/modal_dialog.html" %}
{% block content %}
<div class="p-6 shadow-lg rounded-lg overflow-hidden w-1/3 bg-slate-100">
    <h2 class="text-red-700 font-bold capitalize text-lg align-middle text-center my-2">Delete {{ item.name }}</h2>
    <p class="space-y-4 text-slate-700 text-lg mt-4 mb-8">Are you sure you want to delete the selected item?</p>
    <div class="flex items-baseline">
    <button 
        type="button"
        class="p-2 m-2 bg-teal-700 text-slate-50 font-semibold rounded-lg w-full hover:bg-yellow-600 hover:text-slate-50"
        hx-delete={% url "items:delete" item.id %}
        hx-target="#id-{{item.id}}" 
        hx-swap="outerHTML swap:1s" 
        _="on click trigger closeModal">
        Delete
    </button>
    <button
        class="p-2 m-2 bg-slate-200 text-teal-700 font-semibold rounded-lg w-full hover:bg-slate-200 hover:text-yellow-600"
        type="button"
        _="on click trigger closeModal">Cancel
    </button>
    </div>
</div>
{% endblock content %}

derp/items/templates/create_item_inline.html
<tr id="new-item" class="odd:bg-slate-50 even:bg-slate-200">
    <td scope="row" class="px-4 font-semibold">
        <input type="text" name="name" value="{{ item.name }}" class="rounded-lg w-full">
    </td>
    <td scope="row" class="py-2 px-4">
        <input name="description" value="{{ item.description }}" class="rounded-lg w-full">
    </td>
    <td scope="row" class="py-2 px-4">
        <input type="number" name="volume" value="{{ item.volume }}" class="rounded-lg w-fit">
        <select name="volume_measure" class="rounded-lg">
            {% for option in v_options %}
            <option value="{{ option.0 }}">{{ option.1 }}</option>
            {% endfor %}
        </select>
    </td>
    <td scope="row" class="py-2 px-4">
        <input type="number" name="weigth" value="{{ item.weigth }}" class="rounded-lg w-fit">
        <select name="weigth_measure" class="rounded-lg">
            {% for option in w_options %}
            <option value="{{ option.0 }}">{{ option.1 }}</option>
            {% endfor %}
        </select>
    </td>
    <td scope="row">
        {% csrf_token %}
        <button 
            type="button"
            _="on click remove #new-item"
            class="py-1 px-2 font-semibold rounded-lg bg-red-700 text-slate-100">
            C
        </button>
        <button 
            type="button"
            hx-post={% url "items:new-inline" %}
            hx-target="#new-item"
            hx-swap="outerHTML"
            hx-include="[name='name'], [name='description'], [name='volume'], [name='volume_measure'], [name='weigth'], [name='weigth_measure']"
            class="py-1 px-2 font-semibold rounded-lg bg-green-600 text-slate-100">
            S
        </button>
    </td>
  </tr>

derp/items/templates/item_detail.html
<div id="modal" 
  class="fixed inset-0 flex items-center justify-center z-50"
  _="on closeModal add .closing then remove me">
  <div class="p-6 shadow-lg rounded-lg overflow-hidden w-1/2 bg-slate-100">
    <h2 class="text-teal-700 font-bold capitalize text-lg align-middle text-center">{{ item }}</h2>
      <div class="space-y-4">
        <div>
          <p>Description</p>
          <p>{{ item.description }}</p>
        </div>
        <div>
          <h2>Techical details</h2>
          <p>Volume: {{ item.volume_cm3 }}</p>
          <p>Weigth: {{ item.weigth_g }}</p>
        </div>
        <div>
          <h2>Components</h2>
          <ul>
            {% for component in item.components %}
              <li>{{  component  }}</li>
            {% endfor %}
          </ul>
        </div>
        <div>
          <h2>Other informations</h2>
          <p>Created by: {{ item.created_by }} at {{ item.created }}</p>
          <p>Last modified by: {{ item.last_modified_by }} at {{ item.modified }} </p>
        </div>
      </div>
      <div class="flex items-baseline">
        <button 
          class="p-2 m-2 bg-teal-700 text-slate-50 font-semibold rounded-lg w-full
          hover:bg-slate-100 hover:text-teal-700"
          type="button"
          hx-get="/items/update/{{item.id}}"
          hx-target="#modal"
          hx-swap="innerHTML">Update
        </button>
        <button
          class="p-2 m-2 bg-slate-50 text-teal-700 font-semibold rounded-lg w-full
            hover:bg-teal-700 hover:text-slate-50"
          type="button"
          _="on click trigger closeModal">Cancel
        </button>
      </div>
  </div>
</div>

derp/items/templates/item_inline.html
<tr id="id-{{item.id}}" class="odd:bg-slate-50 even:bg-slate-200 fade-me-out">
    <td scope="row" class="py-2 px-4 font-semibold">{{ item.name }}</td>
    <td scope="row" class="py-2 px-4">{{ item.description }}</td>
    <td scope="row" class="py-2 px-4">{{ item.volume }} {{ item.volume_measure }}</td>
    <td scope="row" class="py-2 px-4">{{ item.weigth }}{{ item.weigth_measure }}</td>
    <td scope="row">
        {% csrf_token %}
        <button 
            type="button"
            hx-get={% url "items:delete" item.id %} 
            hx-target="body" 
            hx-swap="beforeend" 
            hx-trigger="click">
            <span class="material-symbols-rounded text-slate-700" style="font-size: 1.75rem" title="Delete this item">delete</span>
        </button>
        <button 
            type="button"
            hx-get={% url "items:update-inline" item.id %}
            hx-target="#id-{{item.id}}"
            hx-swap="outerHTML">
            <span class="material-symbols-rounded text-slate-700" style="font-size: 1.75rem" title="Edit this item">edit</span>
        </button>
    </td>
</tr>

derp/items/templates/master_file.html
{% extends "core/base.html" %}

{% block title %}
Items-Master
{% endblock title %}

{% block extra %}
<style>
    .fade-me-out.htmx-swapping{
        opacity: 0;
        transistion: opacity 1s easy-out;
    }
</style>
{% endblock extra %}

{% block content %}
<!--BUTTONS-->
<div>
    <button 
        class="mt-4 m-2 p-2 rounded-lg bg-teal-700 text-slate-50 font-semibold 
        hover:bg-slate-100 hover:text-yellow-500" 
        hx-get={% url "items:new" %} 
        hx-target="body" 
        hx-swap="beforeend" 
        hx-trigger="click">Add new item
    </button>
</div>

<!--GRID-->
<div id="grid" class="mx-2 mt-6 relative overflow-x-auto shadow-md rounded-lg">
<table class="w-full text-m text-left table-auto border-collapse">
    <thead class="bg-teal-700 text-slate-50">
    <tr>
        <th scope="col" class="py-2 px-4">Name</th>
        <th scope="col" class="py-2 px-4">Description</th>
        <th scope="col" class="py-2 px-4">Volume</th>
        <th scope="col" class="py-2 px-4">Weigth</th>
        <th scope="col" class="py-2 px-4">Actions</th>
    </tr>
    </thead> 
    <tbody>
    {% for item in items %}
        {% include "item_inline.html" %}
    {% endfor %}
    </tbody>
</table>
</div>

<!--NEW LINE-->
<div class="mx-2 mt-2 relative overflow-x-auto h-8">
    <a 
        type="button"
        hx-get={% url "items:new-inline" %}
        hx-target="tbody > tr:last-child"
        hx-swap="afterend"
        class="py-1 px-2 font-semibold cursor-pointer">
        <span class="material-symbols-rounded text-green-600" style="font-size: 1.5rem" title="Create a new row">add</span>
    </a>
</div>
{% endblock content %}

derp/items/templates/update_item_inline.html
<tr id="id-{{item.id}}" class="odd:bg-slate-50 even:bg-slate-200">
    <td scope="row" class="px-4 font-semibold">
        <input type="text" name="name" value="{{ item.name }}" class="rounded-lg w-full">
    </td>
    <td scope="row" class="py-2 px-4">
        <input type="text" name="description" value="{{ item.description }}" class="rounded-lg w-full"></input>
    </td>
    <td scope="row" class="py-2 px-4">
        <input type="number" name="volume" value="{{ item.volume }}" class="rounded-lg w-full"> 
    </td>
    <td scope="row" class="py-2 px-4">
        <input type="number" name="weigth" value="{{ item.weigth }}" class="rounded-lg w-full">
    </td>
    <td scope="row">
        {% csrf_token %}
        <button 
            type="button"
            hx-get={% url "items:inline" item.id %}
            hx-target="#id-{{item.id}}"
            hx-swap="outerHTML">
            <span class="material-symbols-rounded text-slate-700" style="font-size: 1.75rem" title="Undo changes">undo</span>
        </button>
        <button 
            type="button"
            hx-post={% url "items:update-inline" item.id %}
            hx-target="#id-{{item.id}}"
            hx-swap="outerHTML"
            hx-include="[name='name'], [name='description'], [name='volume'], [name='weigth']">
            <span class="material-symbols-rounded text-slate-700" style="font-size: 1.75rem" title="Save changes">save</span>
        </button>
    </td>
</tr>