derp/core/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from core import views
from core.forms import LoginForm


app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path(
        "login/",
        LoginView.as_view(
            template_name="core/login.html", authentication_form=LoginForm
        ),
        name="login",
    ),
    path("logout/", views.logout_user, name="logout"),
    path("menu/", views.menu, name="menu"),
]

derp/derp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('__reload__/', include('django_browser_reload.urls')),
    path('items/', include('items.urls')),
    path('wearhouse/', include('wearhouse.urls')),
]

derp/core/models.py
from django.db import models

derp/core/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import gettext_lazy as _
from django import forms


INPUT_CLASSES: str = "border block w-full"


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={"placeholder": _("Your user name"), "class": INPUT_CLASSES}
        ),
        label=_("Username"),
        required=True,
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"placeholder": _("Your password"), "class": INPUT_CLASSES}
        ),
        label=_("Password"),
        required=True,
    )

derp/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from .modules.apps import installed_apps


def index(request: HttpRequest) -> HttpResponse | HttpResponseRedirect:
    """
    Home page's view
    """
    if not request.user.is_authenticated:
        return redirect("/login/")
    # TODO: insert index data
    return render(request, "core/index.html")


@login_required
def logout_user(request: HttpRequest) -> HttpResponse | HttpResponseRedirect:
    """Custom view for logout"""
    logout(request)
    return redirect("/login/")


@login_required
def menu(request: HttpRequest) -> HttpResponse:
    """Retrieve all installed apps
    App names are displayed in a dropdown menu
    Each app shows the links to single pages (Items -> Master file)
    """
    if request.method == "GET":
        return render(request, "core/menu.html", {"apps": installed_apps})
    return render(request, "core/index.html")

derp/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>dErp {% block title %}{% endblock title %}</title>
    {% load static %} {% load static tailwind_tags %} {% tailwind_css %}
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
    />
    <script src="{% static 'htmx.min.js' %}" defer></script>
  </head>
  <body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    {% block page %}{% endblock page %}
  </body>
</html>

derp/core/templates/core/base_dialog.html
<dialog id="base_dialog" class="overflow-auto resize">
  <button
    type="button"
    onclick="closeDialog()"
    class="absolute top-2 right-2 cursor-pointer"
  >
    <span class="material-symbols-rounded" style="font-size: 1.75rem"
      >close</span
    >
  </button>
  {% block content %}{% endblock content %}
</dialog>

{% block script %}
<script>
  function closeDialog() {
    this.closest("dialog").close();
  }
</script>
{% endblock script %}

derp/core/templates/core/index.html
{% extends "core/base.html" %}

{% block page %}
    {% include "core/navbar.html" %}
{% endblock page %}

derp/core/templates/core/login.html
{% extends "core/base.html" %}

{% block title %} | Login{% endblock %}

{% block page %}
<div class="px-6 py-8 flex flex-col items-center justify-normal md:h-screen mx-auto">
    <div class="p-6 space-y-4 w-full md:mt-0 sm:max-w-md">
        <form action="{% url "core:login" %}" method="post" class="shadow px-6 pt-6 pb-8 mb-4">
            {% csrf_token %}
            {{ form }}
            <div class="flex items-center mt-2">
                <button class="w-full px-4 py-2 mt-4 text-m font-semibold">Login</button>
            </div>
        </form>
    </div>
</div>
{% endblock page %}

derp/core/templates/core/menu.html
<div class="mt-4 absolute z-50 shadow-lg rounded-lg w-32 bg-slate-50">
    <p class="p-2 italic font-semibold text-slate-700">Applications</p>
    {% for app in apps %}
    <div class="border-t border-slate-400 block p-2">
        <p _="on click toggle [@hidden='true'] on #{{app.name}}"
            class="font-semibold cursor-default text-slate-700">{{ app.name }}</p>
        <div id="{{app.name}}" hidden class="pl-4">
            {% for endpoint in app.endpoints %}
            <a class="font-light text-slate-700" href="{{endpoint.url}}">{{ endpoint.name }}</a>
            {% endfor %}
        </div>
    </div>
    {% endfor %}
</div>

derp/core/templates/core/modal_dialog.html
<div id="modal" 
    class="fixed inset-0 flex items-center justify-center z-50"
    _="on closeModal add .closing then remove me">
    {% block content %}
    <!--Content needs to have a closeModal trigger-->
    {% endblock content %}
</div>

derp/core/templates/core/navbar.html
{% comment "navbar" %} TODO: The navbar currently lacks color styling Postponed
to a time where theme colors are added Also color style lacking for components
{% endcomment %}
<nav class="relative flex justify-between items-center p-2 border-b-4">
  <div class="cursor-pointer mx-2">
    <span class="material-symbols-outlined" style="font-size: 1.7rem"
      >home</span
    >
  </div>
  {% include "core/search_bar.html" %}
  <div>
    <div> 
        <a 
          class="p-2 rounded-md text-lg font-semibold" 
          href="{% url "core:logout" %}"
          >Logout
        </a>
    </div>
  </div>
</nav>

derp/core/templates/core/search_bar.html
{% load static %}
<link rel="stylesheet" href="{% static "css/core/searchBar.css" %}">
<script src="{% static "javascript/core/searchBar.js" %}" defer></script>
<div class="search-bar group rounded-xl">
  <div class="relative flex items-center overflow-hidden">
    <span
      class="material-symbols-outlined cursor-pointer"
      style="font-size: 1.7rem"
      >search</span
    >
    <input
      id="searchbar"
      placeholder="Search..."
      class="search-input h-full w-0 duration-700 group-hover:w-96"
      style="background-color: transparent"
    />
    <!--TODO: there's an eventlistener in the js file because `onkeydown` does not work-->
    <span
      id="eraser"
      class="material-symbols-outlined cursor-pointer mr-1"
      style="font-size: 1.7rem"
      onclick="clearSearchBar()"
      >close
    </span>
  </div>
</div>

derp/core/templates/core/submit_cancel.html
<div class="flex items-baseline">
    <button 
        class="p-2 m-2 bg-teal-700 text-slate-50 font-semibold rounded-lg w-full hover:bg-yellow-600 hover:text-slate-50"
        type="submit">Submit
    </button>
    <button
        class="p-2 m-2 bg-slate-50 text-teal-700 font-semibold rounded-lg w-full hover:bg-slate-200 hover:text-yellow-600"
        type="button"
        _="on click trigger closeModal">Cancel
    </button>
</div>